README.rst
Commit 31a07c9cb8fc ("Rename ebbr.rst to index.rst for html generation")
changed the file name of the ebbr specification rst file, but missed to
update the README file that points to it.
Adapt the README accordingly as well.
Fixes: 31a07c9cb8fc ("Rename ebbr.rst to index.rst for html generation")
Signed-off-by: Alexander Graf <agraf@suse.de>
=> Fix ebbr rst link in README

README.rst
The previous link was pointing to a 404 page: http://www.sphinx-doc.org/contents.html
I wasn't sure whether to keep the `www` part, but it seems this is the canonical URL.
=> Fix sphinx-doc link in README

source/chapter2-uefi.rst
I was reading the 1.0.1 version just released by Grant and I noticed that the URL to the OP-TEE secure storage points to the old documentation location. This PR will update the URL to the correct location at `optee.readthedocs.io`.
// Joakim
=> Update link to OP-TEE secure storage

README.rst
Updated to use Python 3 versions of Sphinx.
Checked on Fedora 33 and Debian 'buster'.
=> README.rst: Python 2 is long time gone

CONTRIBUTING.rst
Main branch of EBBR code is called 'main' so let follow it.
Signed-off-by: Marcin Juszkiewicz <marcin.juszkiewicz@linaro.org>
=> CONTRIBUTING: let wording follow branching

README.rst
'make info' requires texinfo
'make latexpdf' requires latexmk
Signed-off-by: Marcin Juszkiewicz <marcin.juszkiewicz@linaro.org>
=> Fedora needs two more packages

source/references.rst
The current device tree specification is v0.3
=> references: DT spec v0.3

source/chapter1-about.rst
In the scope definition make it clear that we are not defining UEFI but a
subset of UEFI.
=> chapter1: EBBR scope is a subset of UEFI

source/chapter1-about.rst
We describe a design principle applicable to the current release (v2.0) and
not only to v1.0.
=> chapter1: remove reference to v1.0

source/chapter1-about.rst
We already have non-Linux operating systems booting on EBBR compliant
systems since 2016.
=> chapter1: OS independency

source/chapter2-uefi.rst, source/references.rst
The current UEFI specification version is 2.9.
=> chapter2: update UEFI version to 2.9.

source/chapter2-uefi.rst
Most EBBR requirements for device trees are included in UEFI spec v2.9.
We should avoid maintaining these in the EBBR.
=> chapter2: remove redundant DT related definitions

.github/workflows/main.yaml
This branch adds deployment of the current main branch to gh-pages and PDFs to the release page when a new annotated tag is added
=> CI: Add automatic deployment of gh-pages and release PDFs

source/chapter2-uefi.rst
Provide a GUID that can be used in the EFI Conformance Profile Table to
indicate conformance with the EBBR 2.0 specification.
Fixes: #95
Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>
=> UEFI: GUID for EFI Conformance Profile Table

source/chapter2-uefi.rst, source/references.rst
The RISC-V Hypervisor Extension is now defined as part of RISC-V Privileged Architecture specification. Update EBBR accordingly.
Fixes: #100
Signed-off-by: Vincent Stehlé <vincent.stehle@arm.com>
Cc: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>
=> Refresh reference for RISC-V hypervisor extension

source/chapter2-uefi.rst
Add the requirement to support capsule update "on disk" when UpdateCapsule() is implemented.
Also add the requirement to implement the corresponding Capsule* Variables in that case.
Signed-off-by: Vincent Stehlé <vincent.stehle@arm.com>
=> Require capsule update "on disk" and corresponding variables

source/chapter2-uefi.rst
There were a few words too much in the Table 2.1: UEFI Required Elements for the EFI_SYSTEM_TABLE element.
=> 2.1.1: Fix sentence error in required elements

source/chapter2-uefi.rst, source/chapter5-variable-storage.rst
We are still discussing how the location of the EFI variable file should be signaled to the OS.
=> Remove /chosen/efivarfile

source/chapter2-uefi.rst
Make it clearer that even though ConnectController() is not required to support all protocols, it must be implemented.
See #114 and [the call of Jan 15](https://github.com/ARM-software/ebbr/wiki/EBBR-Notes-2024.01.15)
=> Clarify that ConnectController must be implemented

source/chapter2-uefi.rst, source/references.rst
Require the `EFI_TCG2_PROTOCOL` on systems with a TPM.
This is compatible with [BBSR](https://developer.arm.com/documentation/den0107/latest/) `R230_BBSR` for example.
See #65
=> Require the TCG2 protocol if system has a TPM

source/chapter3-secureworld.rst, source/references.rst
Let's deprecate the spin tables for good and allow only PSCI for AArch64.
=> Deprecate spin tables

source/chapter2-uefi.rst, source/references.rst
Require to accept only authenticated in-band firmware updates and mention the corresponding attribute for FMP.
This is supported in U-Boot since a while now.
Also, we require it in SystemReady IR since v2.0.
=> Require authenticated FMP firmware updates

scripts/update_uefi_index.py, source/chapter2-uefi.rst, source/extensions/uefi_index.csv, source/references.rst
Update the UEFI specification version to 2.10 Errata A.
This updates the references, the index script, the index and one reference at once for consistency.
=> Update UEFI version to 2.10 A

scripts/update_uefi_index.py, source/chapter2-uefi.rst, source/extensions/uefi_index.csv, source/references.rst
To follow-up with @xypron's [post on the ML](https://lists.linaro.org/archives/list/boot-architecture@lists.linaro.org/message/3HSIIFYS656Z677TSEAJ7IYGS3ZIIY4O/), update the UEFI specification version we reference to 2.11.
=> Update UEFI version to 2.11

source/chapter3-secureworld.rst, source/references.rst
This is a start at adding requirements on FF-A.
We start by requiring compatibility with v1.2, the version recommended by @achingupta. This is only on AArch64 and only when FF-A is actually implemented.
In the future, we will add more FF-A requirements to support use cases such as TPM-over-FF-A, Virtio-over-FF-A for virtualized environments, etc.
=> Require FF-A compatibility with v1.2

source/chapter2-uefi.rst
Now might be a good time to recommend the graphics output protocol when the platform has graphics.
EDK II and U-Boot support it.
Xen, bootloaders (GRUB) and Linux can make use of it.
=> Recommend GOP
